name: Continuous Integration

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v6
    - uses: extractions/setup-just@v3
    - uses: opt-nc/setup-duckdb-action@v1.2.1
    - uses: oven-sh/setup-bun@v2
    - uses: astral-sh/setup-uv@v7

    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v3

    - name: 'Import to DuckDB'
      run: just csv-to-duckdb

    - name: 'Clean and transform data'
      run: just transform

    - name: 'Install dashboard'
      run: just dashboard-install

    - name: 'Build dashboard sources'
      run: just dashboard-sources

    - name: 'Build dashboard'
      run: just dashboard-build
