name: Daily Update

on:
  workflow_dispatch:
  schedule:
  - cron: "0 4 * * *"  # At 04:00 every day

jobs:
  export:
    uses: ./.github/workflows/export.yaml

  import:
    needs: [export]
    uses: ./.github/workflows/import.yaml
    secrets: inherit

  deploy:
    needs: [import]
    uses: ./.github/workflows/deploy.yaml
