name: Export data from Datastore to BigQuery

on:
  workflow_dispatch:
  workflow_call:

jobs:
  export:
    runs-on: ubuntu-latest

    permissions:
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v5'
    - uses: extractions/setup-just@v3

    - uses: 'google-github-actions/auth@v3'
      with:
        project_id: 'untappd-263504'
        workload_identity_provider: 'projects/937319425064/locations/global/workloadIdentityPools/github/providers/vilnius-pub'

    - uses: 'google-github-actions/setup-gcloud@v3'

    - name: 'Export checkins to storage bucket'
      run: just export

    - name: 'Import to BigQuery'
      run: just import-bq
